# Generated by Django 4.2 on 2023-05-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafacar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appt', models.TimeField()),
                ('endereco', models.TextField()),
            ],
        ),
    ]
