# Generated by Django 4.2 on 2023-05-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rafacar', '0006_agendamento_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='valor',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='preco',
            field=models.TextField(null=True),
        ),
    ]
