# Generated by Django 4.2 on 2023-05-15 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rafacar', '0007_remove_agendamento_valor_agendamento_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='dados_pessoais',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rafacar.dadospessoais'),
        ),
    ]
