# Generated by Django 4.2 on 2023-05-19 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rafacar', '0008_agendamento_dados_pessoais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='appt',
            new_name='time',
        ),
    ]
